language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

env:
  - DB=postgres

before_script:
  - psql -c 'create database tests;' -U postgres

script: nosetests --with-coverage

after_success:
  - coveralls